/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poker;

import javax.swing.ImageIcon;

/**
 *
 * @author alumno
 */
public class MesaJuego extends javax.swing.JFrame {

    /**
     * Creates new form MesaJuego
     */
    public MesaJuego() {
        initComponents();
        jButtonRepartir.setText("<html><p>REPARTIR</p><p>CARTAS</p></html>");
        jButtonVerGanador.setText("<html><p>MOSTRAR</p><p>GANADOR</p></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelJugador1 = new javax.swing.JLabel();
        jLabelJugador2 = new javax.swing.JLabel();
        jButtonRepartir = new javax.swing.JButton();
        jButtonVerGanador = new javax.swing.JButton();
        jLabelSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelJugador1.setText("NOMBRE PLAYER 1");
        getContentPane().add(jLabelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabelJugador2.setText("NOMBRE PLAYER 2");
        getContentPane().add(jLabelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jButtonRepartir.setText("texto constructor");
        jButtonRepartir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepartirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRepartir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jButtonVerGanador.setText("texto constructor");
        getContentPane().add(jButtonVerGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        jLabelSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/equissalir.jpg"))); // NOI18N
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 110, 150));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 110, 150));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 120, 150));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo mesa.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRepartirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepartirActionPerformed
        String numero1="2";
        String simbolo1="picas";
        String numero2="7";
        String simbolo2="treboles";
        String numero3="5";
        String simbolo3="corazones";
        ImageIcon icono1 = new ImageIcon(getClass().getResource("/cartas_poker/"+numero1+simbolo1+".png"));
        ImageIcon icono2 = new ImageIcon(getClass().getResource("/cartas_poker/"+numero2+simbolo2+".png"));
        ImageIcon icono3 = new ImageIcon(getClass().getResource("/cartas_poker/"+numero3+simbolo3+".png"));
        jLabel1.setIcon(icono1);
        jLabel2.setIcon(icono2);
        jLabel3.setIcon(icono3);
    }//GEN-LAST:event_jButtonRepartirActionPerformed

    private void jLabelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseClicked
        InterfazInicio ventana = new InterfazInicio();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_jLabelSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MesaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MesaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MesaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MesaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MesaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRepartir;
    private javax.swing.JButton jButtonVerGanador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelJugador1;
    private javax.swing.JLabel jLabelJugador2;
    private javax.swing.JLabel jLabelSalir;
    // End of variables declaration//GEN-END:variables
}
